### PR TITLE
Added Trajectories addon

### LINKED ISSUE #687: Trajectories API integration
I have seen a few people using trajectories with their missions and for some it means they end up manually piloting parts of it.

eg https://www.reddit.com/r/Kos/comments/2zxw12/gfy_partiallyautomated_first_stage_rtls_xpost/

The trajectories mod has an API we could expose?
https://github.com/fat-lobyte/KSPTrajectories/tree/master/TrajectoriesAPI

### PR DESCRIPTION
**Pull request by CalebJ2**
Fixes #687

Adds an addon that accesses the Trajectories mod via reflection. Provides the following suffixes:
`addons:TR:available`: True if the addon was able to access all the things it needs in the Trajectories mod.
`addons:TR:hasImpact`: True if Trajectories has found an impact position for the current vessel.
`addons:TR:impactPos`: GeoCoordinates of the impact prediction.

Notes & potential discussion points:
- Works with the current Trajectories version ([1.4.6](https://github.com/neuoy/KSPTrajectories/releases/tag/v1.4.6)). Future Trajectories updates may break this addon, in which case `addons:TR:available` will return false.
- Only works on the "Active Vessel" because Trajectories is hard coded that way as far as I can tell.
- In the documentation I link to one of my scripts on github as an example. Not sure if that's against a policy or something.
- I haven't actually tested the documentation. Hopefully it works.

### CODE REVIEW

**Comment by tomekpiotrowski** [comment]
Any chance Trajectories will provide some kind of an API in the future? Can we send a pull request? We use reflection sometimes if we have to, but obviously it's better to avoid it.

**Comment by CalebJ2** [comment]
I found [this](https://www.reddit.com/r/Kos/comments/30z9ma/how_to_access_data_from_trajectories_mod/cpxnyh8) a while ago that said Trajectories used to have an API but they gave up on maintaining it, so I doubt they would really want to add it back.
Trajectories is on github so I guess we could send a pull request.

**Comment by CalebJ2** [comment]
Youen said he would be fine with adding an API so I will work on that. I might wait until he updates Trajectories to 1.1.

**Comment by tomekpiotrowski** [comment]
That's great :) Keep us posted.

**Comment by tomekpiotrowski** [comment]
I'd be willing to merge this if you 1) updated it and solved all the conflicts 2) tested it with KSP 1.1.2.

**Comment by CalebJ2** [comment]
Ok so I submitted a pull request to Trajectories with an API a while ago and recently fixed an issue he had with it, so I'm expecting it to get merged fairly soon. 

Hopefully I didn't mess things up with #1664 too much by adding another commit.

I don't think I'll be able to do more programming until the end of the summer. :( If someone else can see this through that would be great.

This needs to be updated to latest version of kOS, and the docs section saying there is no API (or something like that) needs to be removed.

**Comment by hvacengi** [comment]
No worries, we'll make it work.  It's on the list of things to make sure we get addressed shortly anyways.

**Comment by CalebJ2** [comment]
My API changes have been merged into Trajectories so it now has an official API. 

This addon works with that API, but needs to be updated to the latest kOS version.

**Comment by hvacengi** [comment]
Adding a reference to the API PR: https://github.com/neuoy/KSPTrajectories/pull/67

**Comment by hvacengi** [comment]
Found an issues in the Trajectories source (see https://github.com/neuoy/KSPTrajectories/issues/74) so I'm going to put this on hold until I hear back about how to proceed.

I have a number of review changes that I've made to both the code and the documentation.  These changes are currently stored in my local repository, rather than as comments to the PR mostly because I was just about ready to merge it with my edits.  I'll hold off merging.

For the time being, I am planning on merging as a rebase, because it makes it easier for me to identify the files directly edited by this PR (as opposed to those edited by by other merged commits).  This is a potential issue for repository history however, so I'm open to suggestions about alternative paths.

**Comment by hvacengi** [comment]
While the issues have been fixed in the Trajectories repository, they are not yet incorporated into a release.  I'm holding off on merging my review branch so that we don't release a new feature for which users need to know how to compile trajectories.  I'll publish my working branch a little later tonight just so that anyone who finds this and wants to make it work can use the most recent version, include my edits to suffix names.

**Comment by PBscoots** [comment]
@hvacengi which branch of yours has your working branch changes? I can't seem to find it.  I will download it and do a compile and test of both Trajectories and KOS for this addon. Hopefully neuoy makes a rev release soon so we can get this finished.

**Comment by hvacengi** [comment]
@PBscoots I just pushed it to https://github.com/hvacengi/KOS/tree/pull-review/1603

Be warned however, there will probably be a rebase coming before I push, and I will definitely modify the history far enough to change my "WIP" commit into a legit commit.

**Comment by PBscoots** [comment]
@hvacengi am I able/(should I) to add commits to your pull-review/1603 to add in the orbit and impact velocity bits?

**Comment by PBscoots** [comment]
@hvacengi I am going to add some commits to your 1603 branch to add in those other parts. My commits on the trajectories side have been implemented and he released an update for 1.2. I have tested it with KOS and available, hasimpact, impactpos, correctedvec, plannedvec all work. Im not quite sure what to do with settarget to test it. 
Anyway, maybe sometime in the next few days I will add my bits, test them, then commit to your branch. Then you can finish your rebase after that. If thats not how you think I should do it, let me know

**Comment by hvacengi** [comment]
I merged this via rebase, and apparently didn't close the original PR.  Closing now.

**Comment by hvacengi** [comment]
@PBscoots if you have other suffixes/features you would like to add, feel free to submit them as a pull request against the develop branch at this point

**Pull request closed without merging**
