### PR TITLE
Add string escaping according to string regex format

### LINKED ISSUE #2672: Escaped quotes in string literal are not unescaped
The syntax allows using quotes in a string by prepending it by another quote: https://github.com/KSP-KOS/KOS/blob/develop/src/kOS.Safe/Compilation/KS/kRISC.tpg#L91

This works during parsing but when you try to print the following string: `"foo""bar"` it will show `foo""bar` instead of `foo"bar`.

Is this expected behavior?

### PR DESCRIPTION
**Pull request by thexa4**
Based on: https://github.com/KSP-KOS/KOS/blob/b56c1b5709df897308c579843e02b9e163973484/src/kOS.Safe/Compilation/KS/kRISC.tpg#L91

Fixes #2672

(Warning: has not been tested yet, unable to compile right now)

### CODE REVIEW

**Comment by jonnyboyC** [comment]
@Dunbaratu Does this now allow certain string escapes? Could you give an example? Mostly just trying to keep https://github.com/jonnyboyC/kos-language-server as in sync with master here a possible

**Comment by thexa4** [comment]
It makes this `print "hello""world".` output `hello"world`

**Comment by jonnyboyC** [comment]
Thanks!

**Comment by 7ranceaddic7** [comment]
@thexa4  Is that really the desired result?

I would think that output should be `hello""world`,  no?

**Comment by thexa4** [comment]
The advantage of treating a repeated quote as a single quote is that it allows you to represent all strings. If you use it as-is, you would not be able to write down a string literal that only contains `"`.

The way this is usually solved is by defining an escape character like `\`. `"\""` would then become a `"` string literal. The other option is escaping by repeating the character. An example of this is printf. It uses the `%` character to as a field placeholder. This makes it impossible to print a string that contains an actual `%` character. The solution they use interprets a `%%` as a single literal `%`.

The existing parser syntax seems a lot like the printf case which is why I used this behavior.

**Pull request merged**
