### PR TITLE
first draft of navball mode

### PR DESCRIPTION
**Pull request by erendrake**
This allows you to set the current navball mode, this was started to allow you to correctly select the correct autopilot mode.

### CODE REVIEW

**Comment by hvacengi** [comment]
Two issues when I checked this code:
1) the string in the setter is case sensitive,  So "orbit" returns an argument is out of range exception, while "ORBIT" does not.
2) it didn't actually toggle the mode on my nav ball, and the gettter returns the value that corresponds with what the navball shows.
screenshot34

**Comment by erendrake** [comment]
i guess i was changing the mode, just not the text. Thank you for trying it out. it should work better now :)

**Comment by Dunbaratu** [comment]
I'm holding off on merging this because of the label "Pending Documentation".

**Comment by erendrake** [comment]
yeah, i just havent gotten back to this. i should have time soon.

**Comment by erendrake** [comment]
im going to have to work on this some more.

**Pull request closed without merging**
