### PR TITLE
Rt 17 futures

### PR DESCRIPTION
**Pull request by erendrake**
This is a wrapup of #1102 and #1170 caught up with develop. This gives me a simple way to merge this once the release is out and i can keep it up to date.

### CODE REVIEW

**Comment by Dunbaratu** [comment]
@erendrake - I'm trying to prep a changelog and a milestones list for v0.19.0 and I came across this one as having been updated after Nov25 (the date of last release), but the update is merely that you removed your self-assignment and that's all.  Is this still "Not Ready" and should we continue ignoring it?   This PR's is 7 months old and the recent refactor has changed some things.

**Comment by hvacengi** [comment]
It is my understanding that it was waiting on the inclusion of new features in RemoteTech itself.  @tomekpiotrowski might also know if those changes have been merged and released in RT.

**Comment by Dunbaratu** [comment]
Ah crud I just had a look at the remote tech thread and it's been stuck at 1.6.9 for ages.  These PRs' need it to be at version 1.7.

okay, so still not ready then.

**Comment by tomekpiotrowski** [comment]
PRs on the RemoteTech side were submitted at a very unfortunate time. Looks like Dennis has halted his work on RT until KSP's stock antenna relay system comes out (which has now been postponed until 1.2).

**Comment by tomekpiotrowski** [comment]
Now that RemoteTech 1.7 is out I will re-test this (probably tomorrow).

**Comment by hvacengi** [comment]
@erendrake already did all of the review right?  In theory as long as it works the only changes you should need to do are resolving conflicts.  If that happens I'd say just merge it yourself, unless you want us to take another review.

**Comment by tomekpiotrowski** [comment]
I'm assuming erendrake already had a look at it. If everything checks out I will merge tomorrow.

**Comment by tomekpiotrowski** [comment]
This needs some updating so I'll submit a new PR.

**Pull request closed without merging**
