### PR TITLE
Update kos_theme.css

### PR DESCRIPTION
**Pull request by vincentBenet**
Proposition for css of sphinx

### CODE REVIEW

**Comment by Dunbaratu** [comment]
I am not really knowledgeable about which sphinx's CSS categories apply to which things I see on screen, so I'm not clear on what this does from just reading the code.  Can you give a brief description or screenshot of what these changes are meant to do?  (To regen docs is a slightly messy thing for me because I have to go do it on another computer on the cloud, not my usual dev computer.  I usually only do it when a release is coming out.)

**Comment by Vincentimetr** [comment]
Hi, do you want I send you the result by email as .zip 
After i add some comments if course...

**Comment by Dunbaratu** [comment]
Hypothetically you're supposed to be able to append files to comments in github by dragging them into the comment composing box.  I have no idea if there's a filesize limit to that though.

**Comment by Vincentimetr** [comment]
Well it's been a long time sorry I forgot this post:
I will try to regenerate and send the result here in a few time.

Here some features:

Full size on screen of the doc
Last time reload
Titles and subtitle numerotation
Add logo and header
Multiple toctree for better tree structure
Mouse interraction on clickable links

**Pull request closed without merging**
