### PR TITLE
Sphinx handling sphinx and python versions

### PR DESCRIPTION
**Pull request by jacktose**
This fixes both parts of [#1825][issue] by checking the versions of sphinx and python before doing version-specific things.

[issue]: https://github.com/KSP-KOS/KOS/issues/1825 "Sphinx building doesn't handle new sphinx and python versions"

### CODE REVIEW

**Comment by Dunbaratu** [comment]
Issue #1825 got closed without this PR being merged, which was supposed to have been the PR that would fix 1825.  Can you elaborate?

**Comment by jacktose** [comment]
Oh, huh. It got closed by PR https://github.com/KSP-KOS/KOS/pull/1834, but it doesn't look like any of those commits address the versioning issues. Maybe someone got confused because I submitted two different PRs at about the same time?

Has anyone attempted to replicate issue https://github.com/KSP-KOS/KOS/issues/1825 since that update?

**Comment by Dunbaratu** [comment]
I am not in a position to test this because I'm not willing to upgrade to python 3 on account of other stuff I'm still using 2.x for that has similar forward-incompatibility issues.

**Comment by jacktose** [comment]
Okay, updated to the current develop branch and tried again. I can replicate the issue.

**Comment by Dunbaratu** [comment]
> I can replicate the issue.
meaing?  The problem still exists in develop and we still need to apply this PR?
Again, the problem is I can't do much to test this beyond making sure it doesn't break older installs and thus doesn't make things worse.  I guess that's the minimum criteria to make it acceptable to merge.

**Comment by jacktose** [comment]
> meaing? The problem still exists in develop and we still need to apply this PR?

Meaning exactly that! I commented on the issue to clarify.

> I can't do much to test this beyond making sure it doesn't break older installs

I really hope you will, because I can't feasibly downgrade to Python 2.

**Comment by Dunbaratu** [comment]
Verified that it doesn't break my older sphinx/python setup, so I accepted and merged it.

**Pull request merged**
