### PR TITLE
Throw exceptions when controlling another vessel

### LINKED ISSUE #391: Only allow partmodules to be altered for CURRENT ship
It is currently possible to use the new partmodule system to fiddle with the controls of parts your CPU isn't actually connected to because they're on a different ship.

For example:
```
// open the shroud on a docking port of the target vessel:
target:partsdubbed("that dockingport")[0]:doevent("open").
```

That should only be done by the SCS that is ON that target ship.  A check should be put in place that for a DOEVENT, GETFIELD, SETFIED, or DOACTION to be legal, the part must be a member of the same vessel as the vessel running the code (the shared.vessel).

### PR DESCRIPTION
**Pull request by hvacengi**
Fixes #391 and #1068.
Adds a new exception class for cases where a script tries to access a suffix on another vessel that should only be accessible to the local cpu vessel.

The VesselTarget, PartValue, and PartModuleFields classes now implement a method for checking the vessel, and have had the check added to some suffixes:
- `vessel:control`
- `part:controlfrom`
- `part:tag` (set only)
- `partmodule:doaction`
- `partmodule:doevent`
- `partmodule:setfield`

I think the correct way to document this is to add a warning to each of these suffixes documentation identifying that access is restricted to the local cpu vessel.

I've labeled the PR as breaking, because there may be scripts that previously took advantage of this bug that will be broken.

I welcome any and all suggestions for additional suffixes (including on other structures) to black list.

### CODE REVIEW

**Comment by Dunbaratu** [comment]
I was considering self-assigning this and pulling it, but the only reason I haven't is that it has the "Pending Documentation" tag, which hints at it maybe not being ready yet?  If it's ready, I'm happy to pull it and write the documentation.

**Comment by hvacengi** [comment]
I want to get this merged after we do most of the other changes.  I was kind of hoping that others would chime in with more suffixes that should be protected by this code, so I didn't want to get this branch itself done and then need to go through and add all of the exceptions again.  The other option is that we update what we can in current develop, and then we do the check on new submissions as part of the review.  Let me know what you want, I have a blurb prepared to put it the effected suffixes' text.

**Comment by erendrake** [comment]
other than listing docking ports, im not sure i see why any of a craft's parts would be available to be queried.

Are we worried about reducing the chance to do cool stuff if we hobble the data available to cores on other craft?

**Comment by Dunbaratu** [comment]
> other than listing docking ports, im not sure i see why any of a craft's parts would be available to be queried.

Docking.

When docking with another vessel, you need to know it's docking port parts' locations and orientations and not just the entire target vessel as a single unit.

**Comment by erendrake** [comment]
Alright, then i think this is good enough for now and we should get this documented and merged. We can discuss other suffixes later if we find a need. @hvacengi do you need anything from us on this?

**Comment by hvacengi** [comment]
I don't think I'll need anything.  I'll merge the current develop tonight, then get the documentation noted.  I kind of like the idea of waiting to add more suffixes, mostly because we can see if there's any backlash for the core change itself.

**Comment by hvacengi** [comment]
Documentation has been committed and the most recent develop branch merged.  This should be ready.

**Pull request merged**
