### PR TITLE
one more assembly for development environment

### LINKED ISSUE #2569: KOS build breaks: 'Texture2D' does not contain a definition for 'LoadImage'
> …/KOS/src/kOS/Suffixed/Widget/Widget.cs(23,23): Error CS1061: 'Texture2D' does not contain a definition for 'LoadImage' and no accessible extension method 'LoadImage' accepting a first argument of type 'Texture2D' could be found (are you missing a using directive or an assembly reference?) (CS1061) (kOS)

I'm trying to get my development environment up to speed, and I've had to add a bunch of new assemblies that aren't documented in CONTRIBUTING.md.

My current list of assemblies is:

- Assembly-CSharp
- Assembly-CSharp-firstpass
- UnityEngine
- UnityEngine.AnimationModule
- UnityEngine.AudioModule
- UnityEngine.CoreModule
- UnityEngine.IMGUIModule
- UnityEngine.PhysicsModule
- UnityEngine.TextRenderingModule
- UnityEngine.UI
- UnityEngine.UnityWebRequestWWWModule

Development environment is Visual Studio for Mac Community edition, 8.2 (build 1105)

### LINKED ISSUE #2570: Some solution dependencies are missing from the list in CONTRIBUTING.md
Another Unity version, another patch to CONTRIBUTING.md.

This issue is about to be followed by a PR which alter the assemblies list to the following:

- Assembly-CSharp
- Assembly-CSharp-firstpass
- UnityEngine
- UnityEngine.AnimationModule
- UnityEngine.AudioModule
- UnityEngine.CoreModule
- UnityEngine.IMGUIModule
- UnityEngine.PhysicsModule
- UnityEngine.TextRenderingModule
- UnityEngine.UI
- UnityEngine.UnityWebRequestWWWModule

The PR will also include formatting changes.

### LINKED ISSUE #2580: TipDisplay 404 not found.
Click on ``TipDisplay`` in the GUI:TOOLTIP description, and despite being highlighted as a link to a structure, it gives a 404 not found error.

### PR DESCRIPTION
**Pull request by MaraRinn**
Resolves #2569 

Resolves #2570

This was the last assembly I needed to copy across from KSP in order to make the build work. KSP runs fine, the add-on behaves as expected.

### CODE REVIEW

**Comment by Dunbaratu** [comment]
What's weird is that I do NOT have this DLL in my environment and it builds fine.  It must be something Unity has in their Mac port but not their Windows port.

**Comment by Dunbaratu** [comment]
Hmm.  I shouldn't have merged that so quickly.  I just noticed that I don't have that DLL, "UnityEngine.ImageConversionModule" - It's not part of my copy of Kerbal Space Program at all.

Perhaps the instructions need to be changed to say something like, "Not all of these files exist in all Kerbal Space Program installs because some of them exist only on some OS ports.  Copy all the files that do exist on this list.  If a file mentioned below does not exist on your installation, don't worry, just skip it and move on to the next one."

**Comment by MaraRinn** [comment]
I will get a new PR up soon indicating that this assembly is probably macOS specific.

**Comment by Dunbaratu** [comment]
It's not just that one.  I think in general (not just on one specific assembly) it just needs the comment that warns not all installs have all these assemblies and that's okay.

**Comment by MaraRinn** [comment]
Ah, of course.

**Pull request merged**
