### PR TITLE
stubbed out addon documentation

### PR DESCRIPTION
**Pull request by erendrake**
We are now integrated with two different mods, with more to come. so this is my idea for a start to this documentation.

### CODE REVIEW

**Comment by SirDiazo** [comment]
Makes sense to me. Are there documentation guidelines somewhere I should look at before populating the AGX section or should I just throw something together for you guys to review?

**Comment by erendrake** [comment]
I think right now you get to blaze a trail and we can discuss it. If I
might make a suggestion, a short video would be pretty cool if you are up
for it.

**Comment by SirDiazo** [comment]
Alright.

Let me hash out something and see what's what.

I'll experiment with a video, but I don't have a working mic so maybe an imgur album with overlay notes?

**Comment by erendrake** [comment]
It is all good ☺ don't stress it. having something soon is better than
getting perfection a month from now. I would like to build a new release in
a week and I would love to have some docs with this cool new feature by
then.

**Comment by SirDiazo** [comment]
Alright.

Now, Git questions. I can't edit files on this PR, if I start a new (non-forked) file in my repository, can I PR it to the correct location once the merge of this PR makes it, or should I wait for this PR to merge and then fork it to make my changes?

**Comment by erendrake** [comment]
You could merge the fork on my branch, then work off of that. Or I could
just merge this in the next 10 mins and let you just work off of that ☺

**Comment by erendrake** [comment]
@theodoregoetz Was this the correct way to add a new top level nav item? I admit i havent made the time to get generating the docs locally work

**Pull request merged**
