### PR TITLE
Fixes 1090 by listing bodies as BodyTargets.

### PR DESCRIPTION
**Pull request by Dunbaratu**
This one was simple.

### CODE REVIEW

**Comment by Dunbaratu** [comment]
Saying #1090 so this gets a link to the issue.

**Comment by hvacengi** [comment]
Is there a reason this was done previously using the `ListValue.CreateList` method?  It looks like there is an underpinning to allow you to cast the list items to another type, but I don't know if we have enabled the necessary casting on the `BodyTarget` class.  I prefer your solution, but wanted to make sure we weren't breaking something else by moving away from that convention.

**Comment by Dunbaratu** [comment]
CreatList just turns any generic collection into our ListValue collection, but as far as I know it doesn't alter the individual items within the list, which is what's needed here.

**Comment by hvacengi** [comment]
From ListValue.cs:
```
        public static ListValue<T> CreateList<TU>(IEnumerable<TU> list)
        {
            return new ListValue<T>(list.Cast<T>());
        }
```
If I read the generics right there, you could in theory call `ListValue<BodyTarget>.CreateList<Body>(FlightGlobals.fetch.bodies)` But I haven't tried it.  At for what we're doing, I think it just adds a layer of complication for someone who comes back to look at it later.

I say leave it the way you did it.  Just trying to understand the underpinnings myself having come it late.

**Comment by Dunbaratu** [comment]
There exists a constructor for BodyTarget that goes like so:

BodyTarget(CelestialBody cb, SharedOjbects so);

I don't think we have implemented an automatic casing conversion that will create a BodyTarget from JUST a CelestialBody without being given that SharedObjects information, so the cast you're talking about doesn't seem to me like it would do the job.

**Pull request merged**
