### PR TITLE
Set volume name to kos tag

### LINKED ISSUE #354: Naming volumes from KOSNametags?
Now that parts can be named with KOSNameTags, should we implement the ability to refer to a volume by its nametag?  (The Part on which the KOSProcessor PartModule exists should also have a kOSNameTag partmodule on it too now since we attached KOSNameTags to all parts now.).

### PR DESCRIPTION
**Pull request by tomekpiotrowski**
Fixes #354 

Sets the initial volume name to processor's kOS name tag.

### CODE REVIEW

**Comment by tomekpiotrowski** [comment]
Ah, this actually depends on #1195

**Comment by hvacengi** [comment]
I'm not sure I like this being a set in stone feature.  I personally use the processor's tag to store other data (such as the name of the station it is to dock with).  The user doesn't necessarily want to have the volume named "Babylon 5" just because they put that in the name tag of the processor.  On the other side of the coin, unless the user takes the time to set the volume name directly they probably wouldn't even notice that the name is different.

I think I'd prefer a better way to opt in to this feature, like a config flag.  The alternative would be to recommend that users place the following line at the opening of their boot file: `if core:volume:name = "" set core:volume:name to core:part:tag.`

**Comment by tomekpiotrowski** [comment]
I was thinking that in the end we could totally eliminate volume names. See #1196.

Tags would only be used for identification. I'm working on storing data here #1168 and I have #353 implemented. Those 2 would eliminate the need to use tags for anything else than ids.

**Comment by Dunbaratu** [comment]
I'd rather tags not be used to store data.  It's really a roudabout way to deal with things.  They're supposed to just be used to identify WHICH thing you have, not to store data IN the thing.  I think using it for the volume name makes perfect sense, but it does have one consequence to think about:

Right now we *happen to have* a one-to-one relation between volumes and cpu's.  There's no rule that says it has to stay that way forever.  Maybe we'll have a part that is just a hard drive and stores several volumes?  But using the tag name makes it so that the one-to-one relation is set in stone.

**Comment by tomekpiotrowski** [comment]
@Dunbaratu I see your point.

**Comment by Dunbaratu** [comment]
In retrospect I think it's fine to have the one-to-one relationship because if we ever have multiple hard drives in one unit we can just add more than one PartModule to it, one per drive.  So never mind, the design is fine.

**Pull request merged**
