### PR TITLE
added binding for dynamic pressure

### PR DESCRIPTION
**Pull request by erendrake**
Progress towards #188

This may not actually deal with the FAR integration problem.

### CODE REVIEW

**Comment by hvacengi** [comment]
We should (and I will later today) double check any other values returned in kOS for proper units.  You convert to Pa and most KSP methods return either kPA (as the underlying code here does) or Atm.  I think the units returned should remain consistent unless there is a major reason not to.

**Comment by erendrake** [comment]
Excellent point. What do we think makes the most sense? Atm?

**Comment by Dunbaratu** [comment]
Although ATM is the most human-readable, for most math formulas you end up having to convert ATM into something more universal anyway, and a kOS script is going to be doing math on it, I presume.

**Comment by erendrake** [comment]
So im coming back to this. My thoughts are no matter which we choose we should provide some kind of constant that will let you take the kpa or atm and convert it to the other. 

Right now it seems that we have a bias for display units in the API. Degrees come to mind. Using ATM would fit that pattern. Is that a pattern we like?

**Comment by Dunbaratu** [comment]
edit this to return ATM's -  that was the decision we made in video chat.

**Pull request merged**
