### PR TITLE
removed filePath in KOSTextEditPopup

### LINKED ISSUE #1711: EDIT can cause duplicate files with non-suffixed names
On v1.0.0-pre-1, the terminal save button uses the literal filename, rather than the *resolved* filename, but *opens* the resolved filename.

Repro Steps:
- Add `print "foo".` to `Ships/Scripts/foo.ks`
- `edit foo.`
- Note that `print "foo".` is displayed - the editor resolved the file correctly
- Click "Save"
- Note `Ships/Scripts/` now contains `foo.ks` AND `foo` (no extension)

### PR DESCRIPTION
**Pull request by tomekpiotrowski**
fixes #1711

### CODE REVIEW

**Comment by Dunbaratu** [comment]
Is the fix_edit branch on the main repo?  I can't find it in your fork, @tomekpiotrowski

**Comment by Dunbaratu** [comment]
This fix broke a previously working thing that prevents me from accepting it in its current condition.  If I get time later I'll try looking at fixing it myself because I know @tomekpiotrowski is busy and it's very late at night over in Europe right now (We're trying to get a release of 1.0.0 tonight).

But in the meantime I'll move on to the next PR in case you do see this message in time, @tomekpiotrowski and think you know the problem and can fix it faster than I can.

What broke is this:

- Now the `edit` command is incapable of creating a new file from scratch.

Try:
```
switch to 0.
edit new_file.ks. // new_file.ks does not exist yet.
```

Old Behaviour: Editor Window opens onto an empty file.  If you type something and save it, it makes a brand new filename called `new_file.ks`.

New Behaviour: This exception happens, and the popop window does not appear:
```
System.NullReferenceException: Object reference not set to an instance of an object
  at kOS.Screen.KOSTextEditPopup.DelegateLoadContents (kOS.Screen.KOSTextEditPopup me) [0x00000] in <filename unknown>:0 
  at kOS.Screen.KOSTextEditPopup.LoadContents (kOS.Safe.Persistence.Volume vol, kOS.Safe.Persistence.GlobalPath path) [0x00000] in <filename unknown>:0 
  at kOS.Screen.KOSTextEditPopup.AttachTo (kOS.Screen.TermWindow termWindow, kOS.Safe.Persistence.Volume attachVolume, kOS.Safe.Persistence.GlobalPath path) [0x00000] in <filename unknown>:0 
  at kOS.Screen.TermWindow.OpenPopupEditor (kOS.Safe.Persistence.Volume v, kOS.Safe.Persistence.GlobalPath path) [0x00000] in <filename unknown>:0 
  at kOS.Function.FunctionEdit.Execute (kOS.SharedObjects shared) [0x00000] in <filename unknown>:0 
  at kOS.Function.FunctionBase.Execute (kOS.Safe.SafeSharedObjects shared) [0x00000] in <filename unknown>:0 
  at kOS.Safe.Function.FunctionManager.CallFunction (System.String functionName) [0x00000] in <filename unknown>:0 
  at kOS.Safe.Execution.CPU.CallBuiltinFunction (System.String functionName) [0x00000] in <filename unknown>:0 
  at kOS.Safe.Compilation.OpcodeCall.StaticExecute (ICpu cpu, Boolean direct, System.Object destination, Boolean calledFromKOSDelegateCall) [0x00000] in <filename unknown>:0 
  at kOS.Safe.Compilation.OpcodeCall.Execute (ICpu cpu) [0x00000] in <filename unknown>:0 
  at kOS.Safe.Execution.CPU.ExecuteInstruction (IProgramContext context, Boolean doProfiling) [0x00000] in <filename unknown>:0 
```

**Comment by Dunbaratu** [comment]
Fixed by moving one line down into the if-check for null.  (it was unconditionally calling this:
```
    me.loadingPath = GlobalPath.FromVolumePath(item.Path, me.loadingPath.VolumeId);
```
even when `item` was null because the file didn't exist yet.  The code contained a check for this case (`item` being null because there's no file yet), but the newly inserted line was being called outside that case.)

**Comment by tomekpiotrowski** [comment]
I'm glad you got it sorted out.

 (Yeah, I got used to uploading the PR branches straight to the main repo at work, must have done it without thinking)

**Pull request merged**
