### PR TITLE
Comma-list declarations issue 2856

### LINKED ISSUE #2856: Support comma-list declarations
e.g. this:
```
local a is 3, b is 20, c is "hello".
```
and this:
```
set x to 3.21, y to 50.12.
```
This would be consistent with ``parameter`` which already allows this.

### PR DESCRIPTION
**Pull request by DanTGL**
Added comma-list declarations.

Fixes #2856 

It is not finished yet as I have only added them for `SET` right now.

### CODE REVIEW

**Comment by marianoapp** [comment]
If you made changes to the grammar you need to commit the kRISC.tpg file too. I assume you did since the PR includes changes to the Parser class.

**Comment by thexa4** [comment]
Does this allow `set foo to 1, bar to foo.`?

**Comment by DanTGL** [comment]
@marianoapp I didn't realize that I was supposed to modify the kRISC.tpg file, but I've done it now and generated the code with TinyPG.

@thexa4 Yes, that works.

**Comment by DanTGL** [comment]
This basically works by splitting them up in separate operations, so the only actual changes are how the statement is parsed and compiled. So it basically still functions the same way as having separate statements.

This is basically the only thing I've changed in the code aside from kRISC.tpg:
https://github.com/KSP-KOS/KOS/blob/87e9c021b0bae6cb53749932484577780d3649b2/src/kOS.Safe/Compilation/KS/Compiler.cs#L2175-L2183

**Pull request merged**
