### PR TITLE
Improved RP-1 tech progression

### PR DESCRIPTION
**Pull request by RCrockford**
Changes RP-1 kOS cores to have tech progression that follows the user selected avionics tech.

This requires changes in RP-1 in addition for correct behaviour, but should be safe to merge before that as it will do nothing if the changes are not present.

### CODE REVIEW

**Comment by Dunbaratu** [comment]
I just tried loading this into my RP-1 save (without the associated RP-1 PR, so I could verity that it doesn't break things if this is in kOS but the RP-1 part of it isn't there) and immediately ran into this problem - I cannot get the numbers to appear.  It looks like this (two screenshots included):
screenshot21
screenshot22

**Review by Dunbaratu — CHANGES_REQUESTED** [review]
I think I may have found why when I tested this on an existing RP-1 installation it caused the problems.

**Comment by RCrockford** [comment]
The exception was in some debug logging code that isn't really required ironically. I have removed it, so it should be more robust now.

**Comment by RCrockford** [comment]
The required changes in RP-1 have now been released, so that should make testing this a little easier.

**Pull request merged**
