### PR TITLE
Fixes 2632 ksp1.8 update

### LINKED ISSUE #2632: KSP 1.8 broke kOS.
The KSP 1.8 update that just appeared by surprise today broke kOS.  Because it updates Unity and the version of .net, it may take a few changes in kOS source code to support it.

This issue will be the generic placeholder for getting it to work again.

### PR DESCRIPTION
**Pull request by Dunbaratu**
Fixes #2632 - updates for KSP 1.8 reasons.

(Please note this isn't ready for merging yet. I'm putting it here so others who can compile kOS have a chance to try out these changes before they become public.)

### CODE REVIEW

**Comment by Dunbaratu** [comment]
### Update

I think I need to run PartTools again on the 4 part models we use (for the 4 computer parts).  There was some note about that in the KSP 1.8 modder's notes, and I noticed the shading on the CX-4181 part is all wrong - it has the "sun" shining on the part from the wrong direction so its shading doesn't fit the reset of the cylindrical items in the "stack" it's in.  I tested and this did NOT happen in KSP 1.7.3, so it is definitely related to the KSP 1.8 update.

I haven't run "PartTools" in years and forgot how it works - but I'll have to research it tomorrow.

**Comment by mlheur** [comment]
Build:
- had to change .net target version in my project file, not sure how come git didn't take your updated one
- had to link in more unity DLLs, more than just TriggerAu's list
- EventType.mouse* changed to EventType.Mouse*
- updated version to 1191 just so I could confirm I'm using the latest compiled version and not some stale kOS dll.
- built with ~18 warnings, seem benign.
```
1>------ Rebuild All started: Project: kOS.Safe, Configuration: Debug Any CPU ------
1>D:\u01\dev\KSP\kOS\src\kOS.Safe\Encapsulation\UniqueSetValue.cs(48,21,48,26): warning CS0108: 'UniqueSetValue<T>.Clear()' hides inherited member 'CollectionValue<T, HashSet<T>>.Clear()'. Use the new keyword if hiding was intended.
1>D:\u01\dev\KSP\kOS\src\kOS.Safe\Execution\CPU.cs(1429,25,1429,46): warning CS0184: The given expression is never of the provided ('NoDelegate') type
1>D:\u01\dev\KSP\kOS\src\kOS.Safe\Compilation\KS\Scanner.cs(29,36,29,47): warning CS0649: Field 'Scanner.FileAndLine' is never assigned to, and will always have its default value
1>D:\u01\dev\KSP\kOS\src\kOS.Safe\Compilation\ProgramBuilder.cs(174,28,174,35): warning CS0649: Field 'ProgramBuilder.BuiltInPath.command' is never assigned to, and will always have its default value null
1>  kOS.Safe -> D:\u01\dev\KSP\kOS\src\kOS.Safe\bin\Debug\kOS.Safe.dll
1>  D:\u01\dev\KSP\kOS\src\kOS.Safe\bin\Debug\kOS.Safe.dll
1>  1 File(s) copied
2>------ Rebuild All started: Project: kOS, Configuration: Debug Any CPU ------
3>------ Rebuild All started: Project: kOS.Safe.Test, Configuration: Debug Any CPU ------
2>D:\u01\dev\KSP\kOS\src\kOS\Communication\Message.cs(55,31,55,45): warning CS0108: 'Message.CreateFromDump(SafeSharedObjects, Dump)' hides inherited member 'BaseMessage.CreateFromDump(SafeSharedObjects, Dump)'. Use the new keyword if hiding was intended.
2>D:\u01\dev\KSP\kOS\src\kOS\Communication\MessageQueue.cs(12,36,12,50): warning CS0108: 'MessageQueue.CreateFromDump(SafeSharedObjects, Dump)' hides inherited member 'GenericMessageQueue<Message, PlanetariumTimeProvider>.CreateFromDump(SafeSharedObjects, Dump)'. Use the new keyword if hiding was intended.
2>D:\u01\dev\KSP\kOS\src\kOS\Screen\TermWindow.cs(104,17,104,20): warning CS0618: 'WWW' is obsolete: 'Use UnityWebRequest, a fully featured replacement which is more efficient and has additional features'
2>D:\u01\dev\KSP\kOS\src\kOS\Suffixed\HsvaColor.cs(45,33,45,47): warning CS0108: 'HsvaColor.CreateFromDump(SafeSharedObjects, Dump)' hides inherited member 'RgbaColor.CreateFromDump(SafeSharedObjects, Dump)'. Use the new keyword if hiding was intended.
2>D:\u01\dev\KSP\kOS\src\kOS\Suffixed\VectorRenderer.cs(33,17,33,24): warning CS0618: 'GUIText' is obsolete: 'This component is part of the legacy UI system and will be removed in a future release.'
2>D:\u01\dev\KSP\kOS\src\kOS\Sound\SoundMaker.cs(74,13,74,16): warning CS0618: 'WWW' is obsolete: 'Use UnityWebRequest, a fully featured replacement which is more efficient and has additional features'
2>D:\u01\dev\KSP\kOS\src\kOS\Sound\SoundMaker.cs(74,34,74,37): warning CS0618: 'WWW' is obsolete: 'Use UnityWebRequest, a fully featured replacement which is more efficient and has additional features'
2>D:\u01\dev\KSP\kOS\src\kOS\Function\PrintList.cs(146,49,146,78): warning CS0252: Possible unintended reference comparison; to get a value comparison, cast the left hand side to type 'Object'
2>D:\u01\dev\KSP\kOS\src\kOS\Screen\TermWindow.cs(223,27,223,30): warning CS0618: 'WWW' is obsolete: 'Use UnityWebRequest, a fully featured replacement which is more efficient and has additional features'
2>D:\u01\dev\KSP\kOS\src\kOS\Suffixed\VectorRenderer.cs(346,70,346,77): warning CS0618: 'GUIText' is obsolete: 'This component is part of the legacy UI system and will be removed in a future release.'
2>D:\u01\dev\KSP\kOS\src\kOS\Suffixed\VectorRenderer.cs(350,51,350,58): warning CS0618: 'GUIText' is obsolete: 'This component is part of the legacy UI system and will be removed in a future release.'
2>D:\u01\dev\KSP\kOS\src\kOS\Binding\FlightStats.cs(17,29,17,39): warning CS0169: The field 'FlightStats.stageValue' is never used
2>D:\u01\dev\KSP\kOS\src\kOS\Screen\TermWindow.cs(38,31,38,35): warning CS0649: Field 'TermWindow.root' is never assigned to, and will always have its default value null
2>D:\u01\dev\KSP\kOS\src\kOS\AddOns\AddonManager.cs(14,40,14,46): warning CS0169: The field 'AddonManager.shared' is never used
2>  kOS -> D:\u01\dev\KSP\kOS\src\kOS\bin\Debug\kOS.dll
2>  D:\u01\dev\KSP\kOS\src\kOS\bin\Debug\kOS.dll
2>  1 File(s) copied
3>  kOS.Safe.Test -> D:\u01\dev\KSP\kOS\src\kOS.Safe.Test\bin\Debug\kOS.Safe.Test.dll
========== Rebuild All: 3 succeeded, 0 failed, 0 skipped ==========
```

Gameplay:
- game starts, new sandbox career, make SPH, add KAL-9000.  All good.
- set boot to "/boot/kos.ks"
- launch: {blrup}, telnet 

```
kOS Operating System
KerboScript v1.1.9.1
(manual at http://ksp-kos.github.io/KOS_DOC/)

Proceed.
Undefined Variable Name 'core'.
__________________________________________
           VERBOSE DESCRIPTION
Undefined Variable Name 'core'.
__________________________________________
__________________________________________
At 1:/boot/kos.ks, line 1
print "kos running as ["+core:bootfilename+"]".
                         ^
Called from [Boot sequence], line 1
run "/boot/kos.ks".
```

**Comment by Dunbaratu** [comment]
@mlheur - these two points make me suspicious:

> 
> * had to link in more unity DLLs, more than just TriggerAu's list
> * EventType.mouse* changed to EventType.Mouse*

Because those edits are *already* there in the pull request's list of Files Changed.  (The first one isn't in source code, but is an edit to the CONTRIBUTING.md file that describes how to compile, that gives a list of new DLLs to reference, and the second one (the EventType) is there in the code.

So I'm thinking you might not actually have gotten all the pieces of this pull request.

**Comment by mlheur** [comment]
Thanks, I was using git wrong.  After I figured out how to make my fork align with your fork; everything's working well.  Will do more testing and report back for any issues.  If you don't hear back, no news is good news...

Thanks for your efforts.

**Comment by hugolaurent74** [comment]
Hello Everyone, 
First, i really have to thank you a lot for your job, i didn't notice how much work is behind all those updates. To this direction, may you manage to estimate a date when the fix could be ready, i'm really looking forward (i check every day) this fix to use again KOS for KSP 1.8 !!
Again, thank you for your time !

**Comment by Dunbaratu** [comment]
I have been sick the last few days, which has delayed things.

**Comment by mferrie** [comment]
I would like to try to help. What needs to be done to get a release out?

**Comment by mlheur** [comment]
All my testing has been successful.  I still don't see any weird reflections on parts, not sure why Part Tool might be needed.

As a tester, I'm using this version and would be comfortable to publish it.

**Comment by Dunbaratu** [comment]
@mlheur 

> still don't see any weird reflections on parts

That was referring to not so much reflections as having the light/dark shading rotated 90 degrees from the actual light source.  Like this:

```
Correct shading:                                                                                                                                                                                                      grey                                                                                              --------                                                                                            /        \                                                                                          /          \                                                                                        /            \                                                                                      \|              \|                                                                                black\|              \|white     <<--- direction of sunlight ------<<                                       \|              \|                                                                                      \            /                                                                                        \          /                                                                                          \        /                                                                                            --------                                                                                                grey                                                                                                                                                                                                                                                                                               What appears to be happening with the KSP 1.8 update:                                                                                                                                                                black                                                                                              --------                                                                                            /        \                                                                                          /          \                                                                                        /            \                                                                                      \|              \|                                                                                 grey\|              \|grey      <<--- direction of sunlight ------<<                                       \|              \|                                                                                      \            /                                                                                        \          /                                                                                          \        /                                                                                            --------                                                                                               white
--
```

**Comment by mlheur** [comment]
image
Ok, now I see it.

**Comment by mlheur** [comment]
I'm checking what needs to be done:

1. read TriggerAu's ksp 1.8 modding post, says new part tools for 1.8
https://forum.kerbalspaceprogram.com/index.php?/topic/188933-180-modders-notes/
New part tools will be made available that contains latest part shaders for DX11 support.
Other than that, the same processes apply as always.

2. read up on Part Tool
https://forum.kerbalspaceprogram.com/index.php?/topic/160487-parttools-updated/
Part Tools has been updated for KSP 1.8.0
Link in the opening post above.
NB: Part Tools now requires Unity 2019.2.2f1

3. experiment and learn.  Will spend half a day installing and working with the above.

**Comment by Dunbaratu** [comment]
@mlheur The chief problem is that we didn't actually *have* the sources at first.  They're not part of what Nivekk originally checked in to github under GPL3 for the kOS project.  For extra models that were added later, we have source for those parts.  I think @pgodd might have also extracted the information to rebuild the sources of the two original parts himself and put them under ``src/part sources/`` along with the sources of the parts he added as well (he added the two high-end CPU parts (the "tubeless" and the "KAL9000"), and I think he also re-worked the two original parts.  I'm not sure which files are which there though.

**Comment by mlheur** [comment]
I started approaching the parts from the other direction.  If squad had to patch their part assets, maybe I could diff their 1.7.3 parts against their 1.8 parts; analyze what they did; and come up with a kind of binary patch for kOS part files.  Only issue with that, their parts did not change...  why should ours have to?

...
```
Files Modded KSP 1.7.3/GameData/Squad/Parts/Utility/mk3CargoBay/short.mu and Modded KSP 1.8/GameData/Squad/Parts/Utility/mk3CargoBay/short.mu are identical
Files Modded KSP 1.7.3/GameData/Squad/Parts/Utility/parachuteMk1/model.mu and Modded KSP 1.8/GameData/Squad/Parts/Utility/parachuteMk1/model.mu are identical
Files Modded KSP 1.7.3/GameData/Squad/Parts/Utility/parachuteMk1/model000.dds and Modded KSP 1.8/GameData/Squad/Parts/Utility/parachuteMk1/model000.dds are identical
Files Modded KSP 1.7.3/GameData/Squad/Parts/Utility/parachuteMk1/model001.dds and Modded KSP 1.8/GameData/Squad/Parts/Utility/parachuteMk1/model001.dds are identical
Files Modded KSP 1.7.3/GameData/Squad/Parts/Utility/parachuteMk1/parachuteMk1.cfg and Modded KSP 1.8/GameData/Squad/Parts/Utility/parachuteMk1/parachuteMk1.cfg are identical
Files Modded KSP 1.7.3/GameData/Squad/Parts/Utility/parachuteMk12-R/model.mu and Modded KSP 1.8/GameData/Squad/Parts/Utility/parachuteMk12-R/model.mu are identical
Files Modded KSP 1.7.3/GameData/Squad/Parts/Utility/parachuteMk12-R/model000.dds and Modded KSP 1.8/GameData/Squad/Parts/Utility/parachuteMk12-R/model000.dds are identical
Files Modded KSP 1.7.3/GameData/Squad/Parts/Utility/parachuteMk12-R/model001.dds and Modded KSP 1.8/GameData/Squad/Parts/Utility/parachuteMk12-R/model001.dds are identical
Files Modded KSP 1.7.3/GameData/Squad/Parts/Utility/parachuteMk12-R/parachuteMk12-R.cfg and Modded KSP 1.8/GameData/Squad/Parts/Utility/parachuteMk12-R/parachuteMk12-R.cfg are identical
Files Modded KSP 1.7.3/GameData/Squad/Parts/Utility/parachuteMk16-XL/model.mu and Modded KSP 1.8/GameData/Squad/Parts/Utility/parachuteMk16-XL/model.mu are identical
Files Modded KSP 1.7.3/GameData/Squad/Parts/Utility/parachuteMk16-XL/model000.dds and Modded KSP 1.8/GameData/Squad/Parts/Utility/parachuteMk16-XL/model000.dds are identical
Files Modded KSP 1.7.3/GameData/Squad/Parts/Utility/parachuteMk16-XL/model001.dds and Modded KSP 1.8/GameData/Squad/Parts/Utility/parachuteMk16-XL/model001.dds are identical
Files Modded KSP 1.7.3/GameData/Squad/Parts/Utility/parachuteMk16-XL/parachuteMk16-XL.cfg and Modded KSP 1.8/GameData/Squad/Parts/Utility/parachuteMk16-XL/parachuteMk16-XL.cfg are identical
Files Modded KSP 1.7.3/GameData/Squad/Parts/Utility/parachuteMk2-R/model.mu and Modded KSP 1.8/GameData/Squad/Parts/Utility/parachuteMk2-R/model.mu are identical
Files Modded KSP 1.7.3/GameData/Squad/Parts/Utility/parachuteMk2-R/model000.dds and Modded KSP 1.8/GameData/Squad/Parts/Utility/parachuteMk2-R/model000.dds are identical
```
...

**Comment by GER-Space** [comment]
any other parts that need a new export? 
I only saw this strange behavior on this one.

[kOSMachine1m.zip](https://github.com/KSP-KOS/KOS/files/3785705/kOSMachine1m.zip)

**Comment by pgodd** [comment]
There are multiple explanations.
Suppose you are presented with 3D model translations, developed by an early mod coder, interested in developing an OS for users, and working with limited support from the app devs.
Somehow you make a part that works.
Then suppose a someone who has an interest in supporting a revitalization of that mod comes along, and finds errors in the original models, and with limited support and no fiscal interest decides to re-work the models and revise them to support the latest standard, not once but several times...
And then suppose some dude comes along years later after multiple revisions of the game, and major reworks of the underlying game engine and somehow recognizes a subtle difference between the 20-odd properties attached to light and surfaces, that they themselves don’t even begin to comprehend.
And then imagine that dude starts to act all offended because we didn’t meet his nubile standards.
Hey bro, don’t like it? Fix it, then find faults .
I’ve been where you are. It ain’t all that.
Prodded

**Comment by mlheur** [comment]
@pgodd, I apologize for improperly expressing my emotion.  What you've interpreting as acting offended was actually wonder, curiosity, and an intent to learn.  Do you have any technical input to this discussion?

**Comment by pgodd** [comment]
I have advice.
There is a lot to learn.
I don’t know everything and choose to do a bad job. This is hard. We are trying to do the best we can.
Technical advice?
There are many names and definitions of objects. Planes can have two sides, both potentially visible from both sides and both potentially transparent.
Visible planes have reflectivity, specularity, and transparency. And can be light emitting at the same time.
Some of those properties may not have been implemented in the original game.
That wouldn’t prevent them from being turned on...
That means settings that weren’t implemented in the previous version had no impact on the object’s appearance, but they were perhaps turned on in experiments, but changes weren’t observed in simulations.
This makes them easy to ignore until the Game engine is updated and includes these tools.
My advice is to learn more than I did.
Pgodd

**Comment by Dunbaratu** [comment]
@GER-Space thank you for the new export of the files.  I'm going to be testing this set of files tonight.

**Pull request merged**
